### PR TITLE
refactor: allows upgrading the google provider to 5.x

### PR DESCRIPTION
**Pull request by lra**
## Summary

The google v5 provider is out since October 2023 and provides much needed features for us. But we can't upgrade to it because of lacework.

This allows lacework to work with google v5.x

## Related PRs

- https://github.com/lacework/terraform-gcp-config/pull/84
- https://github.com/lacework/terraform-gcp-audit-log/pull/87

### init & plan in `examples/custom-service-account`

```
Terraform will perform the following actions:

  # module.lacework_svc_account.google_service_account.lacework[0] will be created
  + resource "google_service_account" "lacework" {
      + account_id   = "lacework-custom-svc-account"
      + disabled     = false
      + display_name = "lacework-custom-svc-account"
      + email        = (known after apply)
      + id           = (known after apply)
      + member       = (known after apply)
      + name         = (known after apply)
      + project      = "a-different-project-id"
      + unique_id    = (known after apply)
    }

  # module.lacework_svc_account.google_service_account_key.lacework[0] will be created
  + resource "google_service_account_key" "lacework" {
      + id                 = (known after apply)
      + key_algorithm      = "KEY_ALG_RSA_2048"
      + name               = (known after apply)
      + private_key        = (sensitive value)
      + private_key_type   = "TYPE_GOOGLE_CREDENTIALS_FILE"
      + public_key         = (known after apply)
      + public_key_type    = "TYPE_X509_PEM_FILE"
      + service_account_id = (known after apply)
      + valid_after        = (known after apply)
      + valid_before       = (known after apply)
    }

  # module.lacework_svc_account.random_id.uniq will be created
  + resource "random_id" "uniq" {
      + b64_std     = (known after apply)
      + b64_url     = (known after apply)
      + byte_length = 4
      + dec         = (known after apply)
      + hex         = (known after apply)
      + id          = (known after apply)
    }

Plan: 3 to add, 0 to change, 0 to destroy.
```

### init & plan in `examples/default-service-account`

```
Terraform will perform the following actions:

  # module.lacework_svc_account.google_service_account.lacework[0] will be created
  + resource "google_service_account" "lacework" {
      + account_id   = (known after apply)
      + disabled     = false
      + display_name = (known after apply)
      + email        = (known after apply)
      + id           = (known after apply)
      + member       = (known after apply)
      + name         = (known after apply)
      + project      = "lolo-r-and-d"
      + unique_id    = (known after apply)
    }

  # module.lacework_svc_account.google_service_account_key.lacework[0] will be created
  + resource "google_service_account_key" "lacework" {
      + id                 = (known after apply)
      + key_algorithm      = "KEY_ALG_RSA_2048"
      + name               = (known after apply)
      + private_key        = (sensitive value)
      + private_key_type   = "TYPE_GOOGLE_CREDENTIALS_FILE"
      + public_key         = (known after apply)
      + public_key_type    = "TYPE_X509_PEM_FILE"
      + service_account_id = (known after apply)
      + valid_after        = (known after apply)
      + valid_before       = (known after apply)
    }

  # module.lacework_svc_account.random_id.uniq will be created
  + resource "random_id" "uniq" {
      + b64_std     = (known after apply)
      + b64_url     = (known after apply)
      + byte_length = 4
      + dec         = (known after apply)
      + hex         = (known after apply)
      + id          = (known after apply)
    }

Plan: 3 to add, 0 to change, 0 to destroy.
```

### init & plan in `examples/prevent-service-account-creation`

```
Terraform will perform the following actions:

  # module.lacework_svc_account.random_id.uniq will be created
  + resource "random_id" "uniq" {
      + b64_std     = (known after apply)
      + b64_url     = (known after apply)
      + byte_length = 4
      + dec         = (known after apply)
      + hex         = (known after apply)
      + id          = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

### CODE REVIEW

**Comment by afiune** [comment]
make it so

**Comment by afiune** [comment]
Make it so

**Comment by afiune** [comment]
This needs a major version bump and then all other modules will have to use the new major version. 

Thank you so much for working on this, @lra

**Comment by lra** [comment]
> This needs a major version bump and then all other modules will have to use the new major version.
> 
> Thank you so much for working on this, @lra

Thanks, do you need me to do anything else?

**Review by afiune — APPROVED** [review]

**Comment by afiune** [comment]
@lra I think I am going to look at some other changes really quick and do a major version release, then we will have to update your other PRs to point to that new major version. It will be `2.0.0` so, upstream modules should pin this module to `~> 2.0`

**Comment by lra** [comment]
> @lra I think I am going to look at some other changes really quick and do a major version release, then we will have to update your other PRs to point to that new major version. It will be `2.0.0` so, upstream modules should pin this module to `~> 2.0`

Thanks, I'll update them now.

**Pull request merged**
